### ISSUE TITLE
Feedback from running inference on Win10 

### ISSUE THREAD

**Issue by Norod** [universome/alis#3]
I'm on conda 4.9.2, Windows 10 64bit

In case anyone finds it useful, then:
I had to run 
`conda install -c anaconda cmake `
To get CMAKE into the environment, however, for some reason pip has failed to install ninja from source.

So after activating the environment, I did the following steps which did not get executed due to the ninja build fail:
`conda install ninja==1.10.0`
`conda install tqdm==4.59.0 gitpython scikit-learn`
`pip install gpustat`
`pip install tensorboard==2.4.1`
`pip install -e .`
`pip install omegaconf click`

I was then able to run the inference notebook and generate a lovely panoramic image

To generate the video, I had to first run:
`conda install -c conda-forge opencv`
To get opencv into the environment

The video was then generated and it looks beautiful. 
Cheers!

**Comment by universome** [comment]
@Norod Thank you for the advice! We didn't have a chance to test the model on a Windows machine.
Also, for Windows users, it might also be helpful to check the original [StyleGAN2-ADA repo requirements or installation instructions](https://github.com/NVlabs/stylegan2-ada-pytorch#requirements) since we inherited almost all the dependencies from it.

**Comment by Norod** [comment]
@universome That's very legitimate :) Perhaps adding note to the README.MD that the code is known to work but not tested on Windows? a link to this issue page and/or the original repo's requirements? (Thank you for that, BTW, it's helpful) Anyway, awesome work!

**Comment by universome** [comment]
@Norod yeah, that's a good idea. I added the link to this issue into README.md
