### ISSUE TITLE
How to resume training from provided checkpoint?

### ISSUE THREAD

**Issue by maderix** [universome/alis#4]
I couldn't locate an option to specify the pretrained checkpoint so I specified it in training/training_loop.py in resume_pkl field.
After running the training job, I encounter this error:
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/alis/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/alis/experiments/shinkansen_slide2-b696bbb/scripts/train.py", line 443, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/alis/training/training_loop.py", line 177, in training_loop
    resume_data = legacy.load_network_pkl(f)
  File "/alis/experiments/shinkansen_slide2-b696bbb/scripts/legacy.py", line 22, in load_network_pkl
    data = _LegacyUnpickler(f).load()
  File "/alis/torch_utils/persistence.py", line 190, in _reconstruct_persistent_obj
    module = _src_to_module(meta.module_src)
  File "/alis/torch_utils/persistence.py", line 226, in _src_to_module
    exec(src, module.__dict__) # pylint: disable=exec-used
  File "<string>", line 25, in <module>
ImportError: attempted relative import with no known parent package
```
What is the correct way to specify a pretrained checkpoint or resume from an existing one?

**Comment by ksteinfe** [comment]
I got this working as follows:

1. Add the following line to the "train_args" section of whatever YML config file is being referenced. By default, launch_local.py loads `configs/main.yml`, so you could simply edit that (I created my own working YML for playing with settings).

```
train_args:
    resume: None
```

2. Train the model by invoking the following modified command:

```
python infra/launch_local.py hydra.run.dir=. +experiment_name=[EXPERIMENT NAME] +dataset=[DATASET NAME] num_gpus=[GPU COUNT] train_args.resume=[PATH TO PKL]
```

**Comment by maderix** [comment]
Thanks!  The method is working fine but the error with reusing the provided checkpoint remains as above.

**Comment by universome** [comment]
@maderix Could you please tell how you specify the checkpoint path? Is it an absolute path (i.e. starting with `/`) or a relative path (i.e. like `../dir_a/dir_b/checkpoint.pkl`)? Also, which checkpoint are you trying to use? Ours our your own one?

**Comment by maderix** [comment]
Hi @ksteinfe 

I'm running inside a docker container but that shouldn't make a difference. The dependencies are installed as per the provided environment.yml 

For specifying the resume checkpoint I'm specifying an absolute path for the repo provided checkpoint  /alis/lhq1024.pkl

**Comment by universome** [comment]
@maderix I have just tried to make a completely fresh run of the training and it worked fine for me. Here is the sequence of commands that I used:

```
git clone https://github.com/universome/alis alis-check
cd alis-check
conda env create --file environment.yml --prefix ./env
conda activate ./env
ln -s /tmp/data data
python infra/launch_local.py hydra.run.dir=. +experiment_name=tmp +dataset=ffhq_1024 num_gpus=2 +train_args.resume=https://vision-cair.s3.amazonaws.com/alis/lhq1024-snapshot.pkl
```
If it helps, here is the output I have for this commands on my machine: https://pastebin.com/gcCCTLS3
In this output, there is the following line printed (on line #501):
```
Resuming from "https://vision-cair.s3.amazonaws.com/alis/lhq1024-snapshot.pkl"
```
It is printed by this [code line](https://github.com/universome/alis/blob/master/training/training_loop.py#L174) which means the checkpoint was indeed loaded.
Can it be the case that you launch training somehow differently?

My `data` directory looks like this (it is actually stored in `/tmp/data`, that's why I do `ln -s` for it):
```
$ ls data
ffhq_1024.zip
```

(I used `ffhq_1024` in the above run just as an example because I didn't have another 1024x1024-resolution dataset nearby and this does not make any difference which pictures are being used).

**Comment by maderix** [comment]
Thanks for the detailed steps 👍  This seems to work, I might have messed up the environment creation somewhere.
